const base=(window.TASKYA_API_BASE||'http://127.0.0.1:8000/api').replace(/\/$/,''),chat=document.getElementById('chat'),form=document.getElementById('f'),input=document.getElementById('i'),lang=document.getElementById('lang'),mic=document.getElementById('mic'),events=document.getElementById('events'),cancel=document.getElementById('cancel'),file=document.getElementById('file'),fileBtn=document.getElementById('fileBtn'),webBtn=document.getElementById('webBtn'),voiceStatus=document.getElementById('voiceStatus');let current=null,lastAnswer='',webEnabled=false;
function add(t,c){const e=document.createElement('div');e.className='m '+c;e.textContent=t;chat.appendChild(e);chat.scrollTop=chat.scrollHeight;return e}
async function watch(id){const es=new EventSource(`${base}/task/${id}/events`);es.onmessage=e=>{const d=JSON.parse(e.data);events.textContent=d.event+(d.data?.tool?' • '+d.data.tool:'');if(d.event==='completed'){lastAnswer=d.data.answer||'';add(lastAnswer,'a');cancel.disabled=true}if(d.event==='approval_required')add('⚠️ Human approval required. Review before approving.','a');if(d.event==='done')es.close()};es.onerror=()=>es.close()}
async function postJSON(url,options){const r=await fetch(url,options);let d={};try{d=await r.json()}catch(_){d={detail:await r.text()}}if(!r.ok)throw new Error(d.detail||d.message||'Backend request failed');return d}
form.onsubmit=async e=>{e.preventDefault();const t=input.value.trim();if(!t)return;document.getElementById('welcome')?.remove();add(t,'u');input.value='';events.textContent=webEnabled?'Web search enabled • Connecting…':'Connecting to Taskya AI…';try{const d=await postJSON(base+'/task',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,language:lang.value,web_enabled:webEnabled})});current=d.task_id;cancel.disabled=false;watch(current)}catch(err){events.textContent='Backend connection failed';add('Backend not connected: '+err.message,'a')}};
cancel.onclick=async()=>{if(current)await fetch(`${base}/task/${current}/cancel`,{method:'POST'});cancel.disabled=true;events.textContent='Cancellation requested'};
document.getElementById('speak').onclick=()=>{if(lastAnswer)speechSynthesis.speak(new SpeechSynthesisUtterance(lastAnswer))};
webBtn.onclick=()=>{webEnabled=!webEnabled;webBtn.classList.toggle('active',webEnabled);events.textContent=webEnabled?'Web search enabled':'Web search auto'};
fileBtn.onclick=()=>file.click();
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)mic.disabled=true;else{const rec=new SR();rec.interimResults=true;rec.continuous=false;rec.onstart=()=>{voiceStatus.textContent='Listening…';mic.classList.add('active')};rec.onend=()=>{voiceStatus.textContent='';mic.classList.remove('active')};rec.onerror=()=>{voiceStatus.textContent='Voice input unavailable';mic.classList.remove('active')};rec.onresult=e=>input.value=Array.from(e.results).map(r=>r[0].transcript).join('');mic.onclick=()=>{rec.lang=lang.value==='en'?'en-IN':lang.value==='mr'?'mr-IN':lang.value==='bn'?'bn-IN':lang.value==='ta'?'ta-IN':lang.value==='te'?'te-IN':'hi-IN';rec.start()}}
file.onchange=async()=>{if(!file.files[0])return;const fd=new FormData();fd.append('file',file.files[0]);try{const d=await postJSON(base+'/upload',{method:'POST',body:fd});input.value+=`${input.value?'\n\n':''}Uploaded file: ${d.filename}. Analyze it.`}catch(err){add('Upload failed: '+err.message,'a')}file.value=''};
